#Database
POSTGRESQL_USERNAME: genji
POSTGRESQL_PASSWORD: root
POSTGRESQL_HOST: 192.168.1.209
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: project_college_db_qa

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:5173